### ISSUE TITLE
Publish a release with #182

### ISSUE THREAD

**Issue by BenSjoberg** [bbeesley/p-timeout-compat#216]
Hi! I'm currently unable to use p-timeout-compat in a Node.js CommonJS module. The issue was fixed in PR #182, but it hasn't made it to an NPM release yet. Would you mind publishing a new release with this change?

Thanks! This & p-queue-compat are super useful for some packages that aren't ready for ESM yet. :)

**Comment by bbeesley** [comment]
Hey dude, sorry, I get too many notifications and I only just saw this. Your fix should be published now.
